name: portafolio_gris
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.11.5


dependencies:
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.0.0
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  curved_labeled_navigation_bar: ^2.0.6
  card_swiper: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/gris.png
    - assets/gris_manos.png
    - assets/gris_cam.png
    - assets/gris_sonriendo.png
    - assets/logo_unimar.png
    - assets/nube_title.png
    - assets/gris_academico.png
    - assets/affinity.png
    - assets/bdd.png
    - assets/c.png
    - assets/cam.png
    - assets/codigo.png
    - assets/diseño.png
    - assets/excel.png
    - assets/figma.png
    - assets/flutter.png
    - assets/gemini.png
    - assets/gris_asoma.png
    - assets/planta.png
    - assets/ps.png
    - assets/py.png
    - assets/vs_code.png
    - assets/firma_autor.png
    - assets/gris_tlfn.png
    - assets/EXPERIENCIA_  Diseño de proyecto de ciencias.png
    - assets/EXPERIENCIA_ Proyectos de electronica.png
    - assets/PROYECTO_  DoFind _ Sistema de Servicios Domésticos a domicilio.png
    - assets/PROYECTO_  UnimArcade_ Juego basado en la carrera de Ingenieria de Sistemas Unimar.png
    - assets/PROYECTO_ Juego de deciciones  ¨Salvando al bastardo¨ en phyton.png
    - assets/PROYECTO_ La Gamificacion como herramienta pedagógica en el área de las matemáticas.png
    - assets/PROYECTO_ Organizador de Archivos hecho con phyton.png
    - assets/HOOBIE_ Hacer manualidades.png
    - assets/HOOBIE_ Jugar Videojuegos.png
    - assets/HOOBIE_ Tomar fotos a todo.png
    - assets/ME GUSTA_ Dibujar cuando me aburro en una clase.png
    - assets/ME GUSTA_ Hacer Galletas.png
    - assets/ME GUSTA_ Los pequeños detalles hacia otros.png
    - assets/ME GUSTA_ Salir a comer.png
    - assets/ME GUSTA_ Tomar fotos a paisajes y atardeceres.png


  fonts:
    - family: Regular
      fonts:
        - asset: fonts/YanoneKaffeesatz-Regular.ttf
        - asset: fonts/YanoneKaffeesatz-Bold.ttf
        
    - family: Titulos
      fonts:
        - asset: fonts/Avallon.ttf